### ISSUE TITLE
Having the routes inside the module?

### ISSUE THREAD

**Issue by AlaaHamoudah** [IdanCo/angular-print-service#1]
What changes should I do if I have a module, so the routes are inside that module not in the upper lever of app-routing.module.ts?

The current work doesn't work if the route was in the app-routing, what should I do to make the route accessible in the module?

**Comment by IdanCo** [comment]
Good question.

I've created a separate module for printing, and loaded it in the main routes like this -

```
const routes: Routes = [
   ...
   { path: 'print', loadChildren: './print/print.module#PrintModule', outlet: 'print'},
   ...
]
```

in in the Print module's routes i've added all the documents -
```
const routes: Routes = [
  {path: '', component: PageComponent, children: [
      ...
      {path: 'receipt/:data', component: ReceiptComponent},
      {path: 'refund/:data', component: RefundComponent},
      ...
    ]}
];
```

**Comment by AlaaHamoudah** [comment]
I tried this, but it gives me this error

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined
TypeError: Cannot read property 'routes' of undefined`

The URL I should call is this , right?

http://localhost:4200/(print:print/receipt/111)

**Comment by AlaaHamoudah** [comment]
I fixed it thorugh adding the index to the route
I add this in app-routing.module

```
 {
    path: 'index',
    loadChildren: 'app/content/pages/pages.module#PagesModule',
  },
  {
    path: 'index',
    outlet: 'print',
    loadChildren: 'app/content/pages/pages.module#PagesModule',
  }
```

and inside the module route I add  the route this way

```
const routes: Routes = [
  {
    path: '',
    component: MyComponent,
    children: [
      {
        path: '',
        component: DashboardComponent,
      },
      {
        path: 'print',
        component: PrintedComponent,
      },
    ],
  },
]
```
